name: funfinder
services:
  web:
    ports:
      - port: 8787
    build:
      commands:
        - npm ci
        - npm run build
    run:
      cmd: ["node", "server/index.js"]
    env:
      NODE_ENV: production
    health_check:
      http:
        path: /health
        port: 8787
      initial_delay_seconds: 30
      timeout_seconds: 10
