name: Deploy Assets to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'public/*.jpeg'
      - 'public/*.jpg'
      - 'public/*.png'
      - 'public/*.svg'
      - 'docs/**'
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-assets:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy assets to docs
        run: |
          mkdir -p docs/assets
          echo "Copying assets..."
          cp public/*.jpeg docs/assets/ 2>/dev/null || echo "No JPEG files found"
          cp public/*.jpg docs/assets/ 2>/dev/null || echo "No JPG files found"  
          cp public/*.png docs/assets/ 2>/dev/null || echo "No PNG files found"
          cp public/*.svg docs/assets/ 2>/dev/null || echo "No SVG files found"
          echo "Assets in source directory:"
          ls -la public/
          echo "Assets copied to docs/assets:"
          ls -la docs/assets/
          echo "Checking file sizes:"
          du -h docs/assets/*

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
