name: Koyeb redeploy
on:
  push:
    branches: [ main ]       # adjust if needed
  workflow_dispatch: {}

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Koyeb CLI (official script)
        run: |
          curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
          echo "$HOME/.koyeb/bin" >> $GITHUB_PATH
      - name: Verify CLI
        run: koyeb version

      - name: Trigger redeploy on Koyeb
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
        run: |
          koyeb --token "$KOYEB_TOKEN" services redeploy "representative-vivie/funfinder"
